cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('users.urls')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('supports', views.support_page, name='support_page'),
    path('services-/<int:product_id>/', views.service_render, name='service_render'),
    path('feedback', views.feedback_form, name='give_feedback'),
    path('service_purchased', views.service_purchased, name='service_purchased'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    product_id = models.IntegerField(blank=True, default=0)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name + " " + str(self.product_id)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Service(models.Model):
    product = models.OneToOneField(Product, default="", on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, default="")
    description = models.TextField(blank=True)
    service_id = models.IntegerField(blank=True, default=0)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:service_page',
                       args=[self.id, self.slug])


class Support(models.Model):
    name = models.CharField(max_length=400, db_index=True)
    slug = models.SlugField(max_length=400, db_index=True, default="")
    description = models.TextField(blank=True)
    support_id = models.IntegerField(blank=True, default=0)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:support_page',
                       args=[self.id, self.slug])


class Feedback(models.Model):
    name = models.CharField(max_length=100, blank=True)
    rating = models.IntegerField(blank=True)
    comments = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.name + " " + str(self.rating)

shop/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = (
            'name',
            'rating',
            'comments',
        )

    def save(self, commit=True):
        feedback = super(FeedbackForm, self).save(commit=False)
        feedback.name = self.cleaned_data['name']
        feedback.rating = self.cleaned_data['rating']
        feedback.comments = self.cleaned_data['comments']

        if commit:
            feedback.save()
        return feedback

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Service, Support
from cart.forms import CartAddProductForm
from shop.forms import FeedbackForm
import pandas as pd


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    current_user = request.user.userprofile
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'current_user': current_user})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def service_detail(request, id):
    service = get_object_or_404(Service, id=id)

    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/service_detail.html',
                  {'service': service,
                   'cart_product_form': cart_product_form})


def support_page(request):
    supports = Support.objects.all()

    return render(request, 'shop/product/support.html', {'supports': supports})


# todo
def service_render(request, product_id):
    print("Product ID : " + str(product_id))
    services = Service.objects.all()
    recommended_services = []
    for service in services:
        print("Service Product ID " + str(service.product.product_id) + " Product ID " + str(product_id))
        if service.product.product_id == product_id:
            print(str(service.product.product_id) + " " + str(product_id))
            recommended_services.append(service)
    print("Recommended Services " + str(recommended_services))
    user_profile_id = request.user.userprofile.custom_user_id
    print("User Profile ID : " + str(user_profile_id))

    return render(request, 'shop/product/services-.html', {'services': recommended_services})


def feedback_form(request):
    feedback_submitted = False
    if request.method == 'POST':
        feedback_form = FeedbackForm(data=request.POST)
        if feedback_form.is_valid():
            feedback_detail = feedback_form.save()
            feedback_detail.save()
            feedback_submitted = True
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
    else:
        feedback_form = FeedbackForm()
    return render(request, 'shop/product/feedback.html',
                  {'feedback_form': feedback_form, 'feedback_submitted': feedback_submitted})


def service_purchased(request):
    current_user = request.user.userprofile
    print("Current User : " + str(current_user.conversion_rate))
    if current_user.conversion_rate == 0:
        current_user.conversion_rate = 1
    request.user.userprofile.save()
    return render(request, 'shop/product/service_purchased.html', {})


def affinity(user, userCount, itemList):
    itemAffinity = pd.DataFrame(columns=('p_id1', 'p_id2', 'score'))
    rowCount = 0

    # For each item in the list, compare with other items.
    for i in range(len(itemList)):

        # Get list of users
        item1Users = user[user.p_id == itemList[i]]["user_id"].tolist()

        # Get item 2 - items that are not item 1 or those that are not analyzed already.
        for j in range(i, len(itemList)):

            if i == j:
                continue

            # Get list of users who bought item 2
            item2Users = user[user.p_id == itemList[j]]["user_id"].tolist()

            # Find score.
            common_users = len(set(item1Users).intersection(set(item2Users)))
            score = common_users / userCount

            # Add a score for item 1, item 2
            itemAffinity.loc[rowCount] = [itemList[i], itemList[j], score]
            rowCount += 1
            # Add a score for item2, item 1
            itemAffinity.loc[rowCount] = [itemList[i], itemList[j], score]
            rowCount += 1

    return itemAffinity


def test_func(user):
    itemList = list(set(user["p_id"].tolist()))  # unique items
    count = 5

    itemAffinity = affinity(user, count, itemList)
    searchItem = int(input("Product id: "))
    recoList = itemAffinity[itemAffinity.p_id1 == searchItem] \
        [["p_id2", "score"]] \
        .sort_values("score", ascending=[0])

    print("Recommendations for item:", searchItem, '')
    # print(searchItem)
    threshold = 0.5
    while threshold:
        D = recoList[recoList["score"] > threshold]
        if D.empty:
            threshold = threshold / 2
            continue
        break;
    # print(D["p_id2"].unique())
    for i in D["p_id2"].unique():
        print(int(i))

    product = pd.read_excel('%04d.xlsx' % (searchItem))
    SList = list(set(product["p_id"].tolist()))
    ServiceAffinity = affinity(product, count, SList)
    threshold = 0.5
    while (threshold):
        E = ServiceAffinity[ServiceAffinity["score"] > threshold]
        if (E.empty):
            threshold = threshold / 2
            continue
        break;

    print("Recommendations for Services of product :", searchItem, '')
    for i in E["p_id2"].unique():
        print(int(i))
    for i in E["p_id1"].unique():
        print(int(i))

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">₹{{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Buy Again">
        </form>
        {{ product.description|linebreaks }}
        <a href="{% url "shop:service_render" product.product_id %}" type="submit" class="btn btn-success">
            Support Service
        </a>
        <a href="{% url "shop:support_page" %}" type="submit" class="btn btn-success">
            Support Products
        </a>

    </div>
{% endblock %}

shop/templates/shop/product/feedback.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Feedback Form
{% endblock %}

{% block content %}
    {% if not feedback_submitted %}
    <h1>Feedback Form
        <form id="product_form" method="post">
            <table class="striped centered">
                {% csrf_token %} {{ feedback_form }}
            </table>
            <button class="btn btn-success" type="submit" name="action">
                Submit Feedback
            </button>
        </form>
    </h1>
    {% else %}
        <h1>Feedback Submitted :)</h1>
        <p>We always work towards getting you a better customer experience</p>
    {% endif %}
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Purchased Items{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  <br></br>
  <a href="{% url 'shop:give_feedback' %}" class="btn btn-success">Give Feedback</a>
  <h3></h3>

  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Purchased Items{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ₹{{ product.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %}

shop/templates/shop/product/service_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ service.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if service.image %}{{ service.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ service.name }}</h1>
        <h2><a href="{{ service.category.get_absolute_url }}">{{ service.category }}</a></h2>
        <p class="price">₹{{ service.price }}</p>
        <form action="{% url "cart:cart_add" service.id %}" method="post">
            {{ cart_service_form }}
            {% csrf_token %}
            <input type="submit" value="Buy Again">
        </form>
        {{ service.description|linebreaks }}
        <a href="{% url "shop:service_page" %}" type="submit" class="btn btn-success">
            Service services
        </a>
        <a href="{% url "shop:support_page" %}" type="submit" class="btn btn-success">
            Support Services
        </a>
    </div>
{% endblock %}

shop/templates/shop/product/service_purchased.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Service Purchased
{% endblock %}

{% block content %}
    <div class="row">
        <img src="{% static 'img/green_tick.png' %}" style="height: 50px;">
        <h1>Service Purchased</h1>
    </div>
{% endblock %}

shop/templates/shop/product/services-.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Services
{% endblock %}

{% block content %}
    {% if services.count == 0 %}
        <h1>No Service Available</h1>
    {% endif %}
    <div class="row">
        {% for service in services %}
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ service }}</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional
                            content.</p>
                        <a href="{% url 'shop:service_purchased' %}">Buy</a>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
        <br>
    </div>
{% endblock %}

shop/templates/shop/product/support.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Support Products
{% endblock %}

{% block content %}
    {% if supports.count == 0 %}
        <h1>No Service Available</h1>
    {% endif %}
    <div class="row">
        {% for support in supports %}
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ support }}</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional
                            content.</p>
                        <a href="{% url 'shop:service_purchased' %}">Buy</a>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
        <br>
    </div>
{% endblock %}